DirectoryPath: public
CheckExternal: false
CheckMailto: false
IgnoreDirectoryMissingTrailingSlash: true
IgnoreInternalEmptyHash: true
IgnoreURLs: [
  "^/git",
  "^/latest",
  "^/\\d+\\.\\d+\\.\\d+",
]
